train_file_m: '/mnt/raid/yangcp/data/multioff/ALBEF/train.json'
val_file_m: '/mnt/raid/yangcp/data/multioff/ALBEF/val.json'                
test_file_m: '/mnt/raid/yangcp/data/multioff/ALBEF/test.json'

image_root_m: '/mnt/raid/yangcp/data/multioff/img_b'


image_res: 224
batch_size_train: 16
batch_size_test: 128 

alpha: 0.4
distill: False
warm_up: False

bert_config: './configs/config_bert.json'

optimizer: {opt: adamW, lr: 2e-7, weight_decay: 0.02}

pretrained: '/mnt/raid/yangcp/checkpoint/BLIP/model_base.pth'
#size of vit model; base or large
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
max_epoch: 50

image_size: 224

# optimizer
weight_decay: 0.05
init_lr: 1e-7
min_lr: 0








