train_file: '/mnt/raid/yangcp/data/Harm_C/ALBEF/train.json'
val_seen_file: '/mnt/raid/yangcp/data/Harm_C/ALBEF/val.json'                
test_seen_file: '/mnt/raid/yangcp/data/Harm_C/ALBEF/test.json'

image_root: '/mnt/raid/yangcp/data/Harm_C/images'



image_res: 224
batch_size_train: 16
batch_size_test: 128

alpha: 0.4
distill: False
warm_up: False

bert_config: '/home/yangcp/ALBEF/configs/config_bert.json'
config: '/home/yangcp/ALBEF/configs/config.json'

optimizer: {opt: adamW, lr: 2e-4, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-4, epochs: 20, min_lr: 1e-5, decay_rate: 1, warmup_lr: 1e-4, warmup_epochs: 1, cooldown_epochs: 0}










