train_file: '/workspace/hateful_memes/ALBEF/train.json'
val_seen_file: '/workspace/hateful_memes/ALBEF/dev_seen.json'                
val_unseen_file: '/workspace/hateful_memes/ALBEF/dev_unseen.json'                
test_seen_file: '/workspace/hateful_memes/ALBEF/test_seen.json'
test_unseen_file: '/workspace/hateful_memes/ALBEF/test_unseen.json'

image_root: '/workspace/hateful_memes/img'


train_file_t: '/workspace/twitter/ALBEF/train.json'
val_file_t: '/workspace/twitter/ALBEF/val.json'                
test_file_t: '/workspace/twitter/ALBEF/test.json'

image_root_t: '/workspace/twitter/dataset_image'

train_file_m: '/mnt/raid/yangcp/data/multioff/ALBEF/train.json'
val_file_m: '/mnt/raid/yangcp/data/multioff/ALBEF/val.json'                
test_file_m: '/mnt/raid/yangcp/data/multioff/ALBEF/test.json'

image_root_m: '/mnt/raid/yangcp/data/multioff/img_b'



image_res: 224
batch_size_train: 4
batch_size_test: 4 

alpha: 0.4
distill: False
warm_up: False

bert_config: '/home/yangcp/ALBEF/configs/config_bert.json'
config: '/home/yangcp/ALBEF/configs/config.json'


optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 20, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}










